### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mainawycliffe** [mainawycliffe/nx-toolkits#32]
## Firebase Project Setup

- [ ] Prompt for Firebase Project (If Firebase project hasn't been initialized)
- [ ] Firebase setup for other types - Firestore, Storage, etc.
- [ ] Firebase Hosting Setup (Multiple Apps and so on)
